server:
  port: 8082 # Puerto único para este servicio

spring:
  application:
    name: publicaciones-service # Nombre para Eureka

  # Configuración de la base de datos H2
  h2:
    console:
      enabled: true
      path: /h2-console

  # Configuración de JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # NUEVO: Configuración para conectarse a RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Configuración del cliente Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true